### ISSUE TITLE
Support for partial expressions

### ISSUE THREAD

**Issue by JamesMGreene** [cschleiden/github-actions-parser#18]
While working on a new workflow using the `concurrency` key, I added the following block to one of my Jobs:

```yaml
    concurrency:
      group: staging_${{ needs.validate-dispatch.outputs.headRef || github.head_ref }}
      cancel-in-progress: true
```

Unfortunately, the parser (via `actions-linter`) is marking that line as an issue: 😭 

```
Error: Could not parse /home/runner/work/docs-internal/docs-internal/.github/workflows/staging-deploy-pr.yml:  Expecting: one of these possible Token sequences:
  1. [LParens]
  2. [fromJSON]
  3. [contains]
  4. [startsWith]
  5. [endsWith]
  6. [join]
  7. [toJSON]
  8. [hashFiles]
  9. [success]
  10. [always]
  11. [failure]
  12. [format]
  13. [cancelled]
  14. [Contextgithub]
  15. [Contextenv]
  16. [Contextjob]
  17. [Contextsteps]
  18. [Contextrunner]
  19. [Contextsecrets]
  20. [Contextstrategy]
  21. [Contextmatrix]
  22. [Contextneeds]
  23. [StringLiteral]
  24. [NumberLiteral]
  25. [True]
  26. [False]
  27. [Null]
  28. [LSquare]
but found: 'staging_'
```

I would assume the parser is getting tripped up by the partial string and partial expression nature of the value.  That said, I also believe that GitHub Actions _does_ support a line of this nature, so ideally this parser would consider it valid as well.

For the short term, I've worked around this by using the `format` method within my expression instead:

```yaml
    concurrency:
      group: ${{ format('staging_{0}', needs.validate-dispatch.outputs.headRef || github.head_ref) }}
      cancel-in-progress: true
```
