### ISSUE TITLE
Missing event type: `merge_group`

### ISSUE THREAD

**Issue by aarokorhonen** [cschleiden/github-actions-parser#54]
Given the following Actions workflow definition:

```yaml
name: Run on PR
run-name: Run on PR, ref: "${{ github.head_ref || github.event.merge_group.head_ref }}" # ← Warning

on:
    pull_request:
    merge_group:
        types:
            - checks_requested

jobs:
    # ...
```

The VSCode GitHub Actions produces the following warning on the `run-name` definition:

```
Context access might be invalid: merge_group
```

While in fact the workflow would work fine with the [recently added](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) `merge_group` event.

I tracked the issue to this repository – please let me know if you would prefer me to open the issue in another repository.

I am happy to contribute a fix if it is as simple as adding the new event type into the schema definition file.
